sqlite:
  db:
    webPendant:
      - tableName: auth_user
        DDL: CREATE TABLE auth_user(`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
          `uname` varchar(100) NOT NULL, `password` varchar(100) NOT NULL,
          CONSTRAINT `idx_uname` UNIQUE(`uname`))
        SqlScript: null
        forceImport: false
      - tableName: user_profile
        DDL: CREATE TABLE user_profile(`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
          `uid` integer NOT NULL, `label` varchar(50) NOT NULL, `theme`
          varchar(5) NOT NULL DEFAULT `dark`, `size` varchar(20) NOT NULL,
          `position` varchar(20) NOT NULL, `urlList` TEXT, `adapter` TEXT)
        SqlScript: null
        forceImport: false
