logger:
  level: debug
  savePath: "@/log"
sqlite:
  dbPath: "@/db"
socket:
  disabled: 
    - notification
    - rssSubscription
api:
  allowHosts:
    - api: /common/doNothing
      hosts: ['server-dev.vinoxm.cloud']
  filterDisabled: 
    - authorizationFilter
  apiDisabled:
    - /auth/*
    - /favorites/*
    - /rss/*
    - /notification/*
    - /kuro/*
    - /schedule/*
    - ^/upload/*
    # - /clash/(?!update)
    # - /common/*
    - ^/download/(aria2)/*
  tokenBucket:
    config:
      enable: false
  ipBlocker:
    enable: false
schedule:
  rssSubscribe:
    enable: false
    corn: 0 7/30 * * * *
  clashSubscribe:
    enable: false
    corn: 0 0 0/12 * * *
  ipBlockerClean:
    enable: false
    corn: 0 0/10 * * * *
  kuroGameSign:
    enable: false
    corn: 0 0 0 * * *    
redis:
  enable: true
  host: 192.168.31.110
  port: 6379
  database: 1
  username: default
  password: "redis-mAou5820"
  keepAlive: 30