profiles:
  active: main
logger:
  level: info
sqlite:
  db: {}
  defaultDB: rss
  dbPath: "@/db"
server:
  port: 8081
  cors: true
axios:
  proxy:
    protocol: http
    host: 127.0.0.1
    port: 7890
api:
  defaultSecret: mAou5820